### ISSUE TITLE
Link for notebooks and data sets not working

### ISSUE THREAD

**Issue by jlrp132** [olawaleibrahim/petroeval#12]
Provided link for notebooks and datasets not working:
Google Drive link for notebooks and data sets: https://drive.google.com/drive/folders/18A2M3o7XU2xz-gR3SAJxOFDpDHxf3OLl?usp=sharing

**Comment by olawaleibrahim** [comment]
Hi, thanks for pointing that out. The google drive is currently unavailable, however you can make use of the github repo link provided; it contains both notebooks and data, you can clone the repo to get the data and notebooks.
